Add public instance status check on refresh action
After the public instance was refreshed, we check if the status for all
paths is ok (302 Found).

diff --git a/.github/workflows/scheduled.yaml b/.github/workflows/scheduled.yaml
--- a/.github/workflows/scheduled.yaml
+++ b/.github/workflows/scheduled.yaml
@@ -96,3 +96,24 @@ jobs:
                   
           # Running juju status will show us the current revisions of the charms.
           juju status --relations
+
+      - name: Check Legend Public Instance status
+        run: |
+          wait_for_curl() {
+            url="$1"
+            for i in {1..30}; do
+              # Any request to any Legend Application should be redirected to gitlab.com
+              curl -i "${url}" | grep "302 Found" && break
+              if [ "$i" -eq 30 ]; then
+                echo "Failed to get '302 Found' response status from ${url}"
+                exit 1
+              fi
+              sleep 10
+            done
+          }
+
+          wait_for_curl "https://juju-acct.legend.finos.org/"
+          wait_for_curl "https://juju-acct.legend.finos.org/api"
+          wait_for_curl "https://juju-acct.legend.finos.org/engine"
+
+          echo "Legend is reachable, getting redirected to gitlab."
